[package]
name = "meta-functional-regex"
version = "0.1.0"
edition = "2021"
authors = "arian pourarian <arianpourarian@gmail.com>"
description = "For long regex-es, this is a functional approach to make them easier to read with the help of metas. It also checks regex validity and safety."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
